version: 0.2

phases:
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.war
    - server_start.sh
    - server_stop.sh
    - TestXMLFile.xml
    - appspec.yml
   
  discard-paths: yes
